apiVersion: v1
kind: Secret
metadata:
    name: heartbeat-credentials
    namespace: monitoring
stringData:
    HEARTBEAT_PING_URL: ENC[AES256_GCM,data:dhiNqriaICw8ROERxv8SKMlHrElIPjSak6yEpsCaN6baXuXX8OgUKiRdrovYxw6PqQ==,iv:hTHFlWDKO1QIorZxhgfcY20ZJGsB8XUxGnDpHBit3JA=,tag:R1hatOVkk4Eq0r2je/OmAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU3ZEU3pNbk4rYUZOTFpN
            UWRobW1hRnpjKzZFNzZHS1FGRWpoQXF3T3hFCkxJMGZpZWdndVltR2pHQVBYOCtV
            eDB5MHhaMTJtYW90NnY2VVJKbGpGNGcKLS0tIHJWS3kvTkthaUJnRStFa2tEcy9G
            WmxHSGVvdWlId3loV3h5Y3IwY29TVTgKjrknsVtUrYoY+LqQKhWZdEwUODxjEsvW
            xWE1e/V4ne9hGGggcAjnK+SVFCqOTH3XQRHEwdWnnCJnfz+WbT+D+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v3e4qexfxds5ljz77qfmjdhttpphm0kpcr7wj0n2fafz3kzm0v5qxzwhsn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T14:01:46Z"
    mac: ENC[AES256_GCM,data:PmuSxRKvF3YUHGZ0qPzW5lUx/XnN7fhAgBbZisds8Iz7Jgr7bVNOs8Si+vqmY6ed36JIPqnpakxEAN2UCcVZe5Ej4w2lmHqaPOOmOHfjz4nRu1SBpAOwekIoyjXBEfil6sApAZ7ZjJO/X6iXwvsjNnFQec2q8T6C7VUrNcbM0vg=,iv:DVdRb3c/J3WIdD+dRLO8QKIM2tDOXaXibs5xBclcrro=,tag:TRnpPFU8HU62VQBUPdzZgQ==,type:str]
    version: 3.13.3
