apiVersion: v1
kind: Secret
metadata:
    name: alert-delivery-credentials
    namespace: monitoring
stringData:
    WEBHOOK_URL: ENC[AES256_GCM,data:vbmf0vlJhCeiEPvxRBIs+ZEDvCaPmLgomG2cYLJIgFSNx5Xfkfse9adgpm5ankUNLQ==,iv:K6LbtXUoG1d2YWUxrpu9Zdr5UdHOv4sj5HwcPxn+sCw=,tag:n1YC5q6Mwn6+2dncKX7/zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSc0JXRmhUbGZjeUppSWdl
            dExFdTQyQWZJZ0VjaDRyUmVBa2E5b1h5TEVBCndwZWNGMjgzc01xZUJuMWx3aXpE
            RkwxNHVQSmZGK21EV1pQZmZLSEtOeDAKLS0tIHdZeFNweCtGOHc5VGl3bk9WcFdN
            SEtmdUJBTmtIUG43T0JXWVVnWndIa1EK4w0Lq5pZYu4QO7Uwn7wCGJe99F/pZ8KY
            oO4uSrTzZDhDxrj0alV5a62942pmZVoz/zaxJP8C5Xed8ABLZ09HzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v3e4qexfxds5ljz77qfmjdhttpphm0kpcr7wj0n2fafz3kzm0v5qxzwhsn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T13:59:26Z"
    mac: ENC[AES256_GCM,data:HKjIkQBiqI2kWhmcmPN60wRziWVlytAmnvKJDqC3NkwQEG/bJ6fLBOXSwcolyCdzmbMGzV8hXHMIcbNrcYwQaBBX0SQgLyL/UHIEhZCdHkwdZ1yBB/XTwnzjLnHT26Xj/O9VdZWU048MxbBpDF7QVDtBFuj6y1LRwy3E+A8wymM=,iv:qFaPxXDrb5xK8f7IPIsWuFDgMDLO0lJlIoSzWMOtpDg=,tag:dMjOov715kmbCRlaea1SHw==,type:str]
    version: 3.13.3
