apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-observability
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./platform/observability
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: platform-crds
  wait: true
  timeout: 10m0s
