apiVersion: v1
kind: Secret
metadata:
    name: dyndns-credentials
    namespace: dyndns
stringData:
    TSIG_SECRET: ENC[AES256_GCM,data:WiDvpxvwWkQAgEY2PIf0DFV2lduUZVOY5fJSdi8li9zFFJrqG5M=,iv:s5zBAt3iy/ccsxc6SAuZ8P2GkU739bRYJ9GuvbN13fc=,tag:rUI23yQdTkxsjqSdGieR6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQ3g4ZWNyU3AxZVVvaW9i
            cVk0M2VXL2xOeXVSbXR2bk1PV0JGL0l1QW1zCmFpMDFtNkxiZHdKeFYrdFdoVEdQ
            bTVoS2NYQVZkWWs4c1VqeG5WRXFwSkkKLS0tIDRsU1laTTVaSVNFV1lSMU1tc1Jl
            NzZPdGR5K0JCVFVZbEVKaHZyb014d1EK1uL6Yt0YSdaYAuZsD+L3IfuhUCUzd0Yh
            sT7M6/IG96ShvWuzUXX5FtvmMAzwNRIpyoEOZE0Is3VprT8/5Wa9MA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v3e4qexfxds5ljz77qfmjdhttpphm0kpcr7wj0n2fafz3kzm0v5qxzwhsn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T13:23:28Z"
    mac: ENC[AES256_GCM,data:ACWwNvg6eyfyb2LBEcTAouGl7txRP0DYRgHLoWZDetJBh0VzJmPx2fEfVX++qVciR4sSjHnGjUDzQjRkbag2auklIunpQ9Zfpo0sDWNkQ/M4xIXeh1br82BTg6EKy6oVxvOGfu20yN5oz9bym7IsQKmQzQoGJ2F/XrE57TsQsl0=,iv:eR7eh0aoO2s/WP81BdxW8iClE961mBbJ4qwJBMSMDQk=,tag:dWzqsVe4riwqtcuGhlF4Vw==,type:str]
    version: 3.13.3
