apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - scripts-configmap.yaml
  - backup-cronjob.yaml
  - prune-cronjob.yaml
  - check-cronjob.yaml
