apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc-credentials
    namespace: monitoring
stringData:
    GF_AUTH_GENERIC_OAUTH_ENABLED: ENC[AES256_GCM,data:uW6DgQ==,iv:NHgyGIshlrrd8e4kpWFp5xJ+oIqG1di9Tn1XejuibOY=,tag:s/Tb4D09OoqY3QUrMZun8Q==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:UYSEJSXnaVh4zlpT150FRwDMEG3Ez1i8A8jLXuDCRh/HSyBvZHsfdBjTKG9iA5zfGtTVg78MHAk=,iv:yXOsaN5/PAgZ29Icn4taQ7KBDcUDr/ehysS1UEVIRpA=,tag:x/COeXtJlLtVsMXVmIRFhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUVg5a2F1ZXBFU2NzWHJS
            bDJ5QUV6cGI0dy9CMFpxRHZzMnhEOGxPK2h3ClJUK09jQnN4V1VCVVpMZ2ZiQ3hU
            dGs1L3lUajl6Qis1L2d0RDNZUWpzSFkKLS0tIGt0ZHNZQkdLR3puZnl2R3lReXhT
            Um9RMjZQTnJqWjRzeXFLM1FnWU5Fb0UKtKeB885KK9pXDobjAr6LT2TfGiyp/s6V
            +UJ2rcxFVZHXYud0H2fabO/XjT6H6QJhw29t25AHkISFccGVj484Fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v3e4qexfxds5ljz77qfmjdhttpphm0kpcr7wj0n2fafz3kzm0v5qxzwhsn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T19:37:41Z"
    mac: ENC[AES256_GCM,data:vLztmM+AHl89g7Hwp/UFoEOvIhsnKcT3PC7Hzh5j+YZ/EGI0iPRVRBv2vwzOxkQqxo/UL5qlWsJCEZRVAXagzJMRhsN5TZKj/69jjpeGU90fLZqLzdBsjkTxXvaGKMqRFQOCdxbrceSC/6EPgEFmAgxDKPZUPJjtdC/Yv5CgyMw=,iv:Qc3VBzNjcd6up7c3nonF22Y5ShL+sdAK0zgfdKcr4kY=,tag:bMNfk+Rupi2UdxXaKGvz4A==,type:str]
    version: 3.13.3
