apiVersion: v1
kind: Secret
metadata:
    name: ups-credentials
    namespace: monitoring
stringData:
    NUT_USERNAME: ENC[AES256_GCM,data:iNGaDSBszSiWWe0=,iv:3sCMDjLXhMjQGnBnYaNeeQVx7m65g27+rpk6eZp0FeM=,tag:jFyk+vnSsnTsl5dOLsxZKA==,type:str]
    NUT_PASSWORD: ENC[AES256_GCM,data:O7AkQ2X66muama7Utx3lWr/mBt8Ik0Skf7xet+iWZ14vcGkUjgrToFyP6AQ95v0YNQ==,iv:XsFbW5UWveosv1YJ377p/YQFnOzflk3l+lKU5XCVXdU=,tag:oKIpaxtHr9/6KhkHGDLx+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrL3FhOFJxaUJwalZRK1Vt
            Y3FDai96VGtqUkNDTDBBSmVNdnlyRUJHSjJjCi9qZGJndDhLeDFGS08yVGt2S0tJ
            dStwR3pEL2tMTlRvRGZsTlJBbHlEUVkKLS0tIHpkVkUvY0FzYU50Qm5xMzF2MUl3
            QWZ4c1VVbWJzUDAvZWRKektKNEZUN1kKRxdZPeRBkr0idAhVFQ+NzeCXpTq5sRn3
            XLQYyduAx8iXfDjtdNTJWcCIs1C9YE0YOx6G89Lui25IpSaaw/mpfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v3e4qexfxds5ljz77qfmjdhttpphm0kpcr7wj0n2fafz3kzm0v5qxzwhsn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T02:26:19Z"
    mac: ENC[AES256_GCM,data:/oHUf64yOTrB5Sr42we+Q9mwPqKdHqciXIIMxKbWB+DLTnrBe5oleskXa6Hvsu5gRKBJ27qjfN424DhIPRRsj2ioIyuzx4RXNaiCrgepNmJs3YPtiRIdHL4wHd+/2GERqbbqkk/WkxzwZuYXUTEtb71N33nU/I2LGNK4mk2Jenw=,iv:32AiB1/w1UK8Mp3WdkZ5ETP+d+8BWMXo+JFVxWprYWM=,tag:PIdhmHovktUB+bhusaMxPQ==,type:str]
    version: 3.13.3
