apiVersion: v1
kind: Secret
metadata:
    name: restic-credentials
    namespace: scrap-backup
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:b1ql0Xuj9DO6BJK74+hdmkpOG1zNral3mUvKEk03ookm87Wzbw==,iv:eGQwYoJC7nsX42L8hPxJCAilZilqzr5/0RC//tkeUhQ=,tag:3gjlZAQirQOhUpZ8cFLVSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTndtZUpZZEs5VEFFRkp1
            UjFOQnljSDg4cWNYSndyRm5NZDAzVUxUUVZ3CnJ2MnJvMnE3QUEzREVaSVJIRkpN
            cmo5Rlg4MnM5cEJFenlFNFVRbEVOcmsKLS0tIGNPLzR5aFZCQWptQ1owb3A0akhF
            OGF0Q1hXRk1Kd1NMUmthRElCaW02b1EKtGpwPlc5CniQsiurLEN6fYBc4ufLd5nD
            umJDIlLGj+9aprfZxuIFnP/rRrXBwchHvytH3jT/x/8JS+ctWzS4Gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v3e4qexfxds5ljz77qfmjdhttpphm0kpcr7wj0n2fafz3kzm0v5qxzwhsn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T01:58:26Z"
    mac: ENC[AES256_GCM,data:pJRNnmV1BzwVX3Asdmmx+l4TlyqVFcJ82vveJqGGrS55D+RpN+FuPNmR+TbXtdtU8NR6uz+kp0CkmhmadqhNICalxXThPaNLrajkplN/iUPsI39TRzn/e/Bjr4RTWCYTaWHP6hCF+EqLWNTPk2DHWYzbjHy9vz5j1elmihIT8UQ=,iv:PJxMHmXq9pIT83PH36aBT0dAaFuF6rATEMCX3bsZuWg=,tag:3JZszB6zCcKpoEhHEidDFQ==,type:str]
    version: 3.13.3
