apiVersion: v1
kind: Secret
metadata:
    name: identity-credentials
    namespace: authentik
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:Wm7xRaQslq2Huoxa92u0TmGo2X6iJ+3nhAEjSx4fJ0kC328Q1kcGKU0Kg87VXkkWEuBHS7GksZ61dvNPBYrK8+fhEA==,iv:XL4f2lG38hM/r/RfQh6+chrFB9QmUlmnTqO6pd+EVk8=,tag:BTFKF57xmkQQp3M67TdWyA==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:lv1OvyjaI3a3S3wi/BqI93WisxwWGA==,iv:Plx4SSL+WBn9PsTgGbEQMbTpnYa6pKsaqPvndff6idE=,tag:nIylZqyXPnOJ5L/pCAgXvA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:4R/6nwkiuDNdLy76ysUGs6PbBgHnVTQAlr6c1NO8RoU=,iv:QblzwMFVmEYVJ8gdoGpJCvT8GGpZPfEghyooTm85vAU=,tag:zbhiS7sWSAj9qiN6rZkMpw==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:DHVdFVwKuNfTqC8Wit4nSDw/9kC84pPh64XjRvNtsHN85SbwJsuk1qMj2Q==,iv:C3a99JYFA4zu+GK7G0IgeQAcjzMeRiCDFuvSaxulBvw=,tag:uviIWwTjppVHXtubh0vLkg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:rlgop9fO8ZcJeoTCp+jI82n4Yka3hq2F0tg/bqr7Dfc=,iv:PMt0YfB43Du4XoE2Md7huVNOkE+bRstgszF5uBpRraI=,tag:nRiyLwNc1pcCaistLDvqMQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:x5wEi/LPOUN9UDrb8EneamlquQN3+piAz3zDjiwO0NA=,iv:U/46ybWwmAYpJX7toStn7UAhlYUeONOBbzB1E1rrato=,tag:FF4iKVd0+d84rpqH+PT2vA==,type:str]
    password: ENC[AES256_GCM,data:lIw6JdTq6+59Za/AwZuuzY8nYYmVMh3uNE+UQkWcPWQ=,iv:gF3Di7jCuW3rhZTndRMfAkDUVNkrVNS9wyNmAlzAKnU=,tag:FwPHb/opFGDxx0bFHdmCOg==,type:str]
    GRAFANA_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:JACM7CjptgofcOM9Q7w9k5fd5exU9r/KEFl6aIWSF9C3BJ1TY9M/Xh1t7S/ZEesvgd642CLwmk0=,iv:YKHHr/qV+dh95RsWQAUSmbqUSGKzfrQ3OO0hJ79HWIQ=,tag:8OW5B6SQggM93urRTCQ6Lw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOXo2Nk9IZkhwK3FaekYw
            cDNQSDhROE1NYVdUek1wYXpBTisxT29oRGxVCmFqeHNUT2szSmx6Rk9jY2t4U2xQ
            ME9xeVFOU1RSNVJjdldvQm4yKytwQjAKLS0tIGNFemlxclhXOWh2RnFWWmJjd3o4
            eE4rR3l2c0hzZ2tCQXpqK3I0Y0hrYW8KqLSycj5uhS0gBEdJmSl/agbVqRu7u7/p
            J7+c/KIgAVTD2VJ2Bowest5pXoHHhmNWKMzZRYmz4MvuvA1cm32j+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v3e4qexfxds5ljz77qfmjdhttpphm0kpcr7wj0n2fafz3kzm0v5qxzwhsn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T19:34:41Z"
    mac: ENC[AES256_GCM,data:mhpmq7yYGFSbk74Rvdb2tNedHyNHRM+z/C+KtO9zYA692q5F520rKp6S0GwAxRw2mCzVJuBVilrC5F0LXNnWTSVJ7fPzHhReXRWHEdv8uZbK8vMd+kj+rQJG/cJQNngSbh3efgZGVnlpDp4lrWUwHYl5sehjmUw11Vpv6oX3RWQ=,iv:UbQJQnxe8K4lEruy0a+lRVfv7S9IHs0J05BY2Tm1VDg=,tag:rJI2dQf0e0ZdCDU64662xw==,type:str]
    version: 3.13.3
