apiVersion: v1
kind: Secret
metadata:
    name: identity-credentials
    namespace: authentik
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:nHQiWSix6fGISklXbm/K7oVveygxi1m3B8qpoXwnFm2Qi6J20STBlaFKkqHLxf8C4M0gqOXBVdVIDhGvGgY7SkMOng==,iv:i0xGnWWFS8tON/ast+X9pegsrM4oCHAJIcd5fmjIe+0=,tag:hDMGtg+cr+D+q9cACr5QZg==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:HBvAEympyHEyPm79CClvMe3fD5UgLg==,iv:cluPBm8Y3C4tD1H7g2p+lPC3iESiYvuop6FWu+/IMtk=,tag:IWhv6ERH3fnvotzeoNnGrQ==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:DMexj+zLCW7sRwpyC1PYozT+i7saCSAg3yUo7GW3azo=,iv:0yCg2sB+o9Nj0ciEdkG+Mx4q6Yp4bBNAdAkqoKEYysA=,tag:nezEh3yrqmhbOShCZOHOUA==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:q3/ntWAiV0lcai0OMd+RpHWv8YHRpfqSdyOcyPli4Oft6ui7hurDabSajA==,iv:C1mkbh3LkOIjoM5OBRavWyY3o3rs+JWPjlPRMJ4CMtY=,tag:k7eBLuS4CgH79y3p8tV/rA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:TmundPdmrKHabeRceymzkFHOpHrpajxmMwHqfbfvq8Y=,iv:90dvVTt/nynEaK2ujDa5kLpm4qWAHcC51C4e33Jkmyg=,tag:UJiT10ozAwQus0QVZ345cg==,type:str]
    postgres-password: ENC[AES256_GCM,data:NN9MAAwgXDF0v+zhKFObaF7GTU79ehS24dCG6fnprLk=,iv:ON3MeK1JAQAwyituNJXA38ne6/JFcvb6FqK4as80Ae8=,tag:ZjbTm68CJZpHP/UxM4Uw+w==,type:str]
    password: ENC[AES256_GCM,data:VZJO0L1lbdN81CnganitqJG8+p5J3ru0HrEeJDDlJ6A=,iv:6z7LM6pOrPCdVYXjrQURVKhytgAW5HW9iNf+3ZO4OAI=,tag:3uBjmeP2u/gOAW8QCrG1eQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcGdSY1NLbzZIVG9hRUwz
            RWdTcFZxYXI5cHBlTXU4WitwUm1pcnBJVTBJCkVzWTQrYUd4QVQ0c2hZcU1PeTdj
            bWNMYWJHdngrWm5hYVl2bzdWc1kveEUKLS0tIFhTRnUxVUk5Z2RqVkZ4OVpSNXla
            QmhSM2FlcnpoMXRYT2FibzJxcE0rQVUKLc8s7NHSHehLNHj4hZeuLjeIRQ901DOZ
            RGEt08+tnsI5n3OZQNYjxI34cu1Pytq+c437v4epjdmEpWSHHNeUNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v3e4qexfxds5ljz77qfmjdhttpphm0kpcr7wj0n2fafz3kzm0v5qxzwhsn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T13:59:15Z"
    mac: ENC[AES256_GCM,data:+x/Teo+DG9yiS2oxvs8rul+Kn68QUGAqXiV3Ta0sfo+URejd7HM7VRUdbf597jP1Fv7YtzYuMTwvUuJoMz7pKM6awJIDEef/s0tsXPWTjtlU8BCGFOMm/azv3q4z2lF8BHMJm/tLHTOiAJvH1oZBQkxeu1xws4lYppNcJQZ4/X4=,iv:MNdJPHO3K8eYxB0sj99P3WVmt9WqcW1AEaHwEbvWqYg=,tag:z0TQ7Xc7PI4myoZdwfTcxA==,type:str]
    version: 3.13.3
