apiVersion: v1
kind: Secret
metadata:
    name: public-tls-credentials
    namespace: cert-manager
stringData:
    TSIG_SECRET: ENC[AES256_GCM,data:dmoozGMobXj3zTOmm+c27rwP+XR6QsqrhsLAUXEKYJV8ZU9lPzjkIyqfeio5Pux51uZfPrDxHA==,iv:cr03HieooXFskMUz03LViOfm3sOT7414ppJ3Eq6TlrY=,tag:GjteZBpMqXFV8md1KivI9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUXp6c21COWJFUTBUTS9B
            WjBzTm1DWUxJRkorbEZ1SThNZmNXQjUwUW1RCkh4TkphdjY3cVAzQk1HeG1zd1pH
            bDJOYjkzNkNLZmxBZXk3M1RhVUFYYzQKLS0tIDJGSGY4dVlOc3Z4NDJzb0hiZjBZ
            Nzd6ZzhQbldyUXM4dDdBMVczc05VbkUKQFC1uFkGASRODnv/7LTzSNWr2P9+W6Vp
            6QnVfqWBrCsnZ0vG0VQ+9RWf3Q+DBXINuNlvwPcH8VNXkdL6b/2elg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v3e4qexfxds5ljz77qfmjdhttpphm0kpcr7wj0n2fafz3kzm0v5qxzwhsn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T14:47:45Z"
    mac: ENC[AES256_GCM,data:1DegFaX7MsQ3cV6x+WtN25wh8Tqz341HmBDj2AaQWIypbdA6kbldJa5Oh7/vOCkQjwVG89xfwR3euK74kUpq7Qo76udKAmiSwy96NItonpxs2i9nubyJBINzG7DYRCQdIlQTWRmEIXkF4y0lJEfTWs7KFMlsN5cYTOPyjT5KQf0=,iv:K0Rwmtj6q9735uoj+VP1sg787SOON9QYyTR4BPNR+rs=,tag:njlZa9BQS/4w+U5MMWqIig==,type:str]
    version: 3.13.3
